# Generated by Django 3.2.4 on 2021-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='name',
        ),
        migrations.AddField(
            model_name='reader',
            name='search',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Please Enter the sentence'),
        ),
    ]
