# Generated by Django 3.2.4 on 2021-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreader', '0002_auto_20210610_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='search',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='provide a brief one liner about your research.'),
        ),
    ]
