# Generated by Django 3.2.4 on 2021-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreader', '0003_alter_reader_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter your full name please !'),
        ),
    ]
