# Generated by Django 3.2.4 on 2021-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreader', '0004_reader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Papers you need'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Please Enter your Full Name'),
        ),
    ]
